### ISSUE TITLE
concurrent requests limit of Twitter-Flinage

### ISSUE THREAD

**Issue by hliu20** [twitter/finagle#332]
I create a thrift server using Finagle like this

val server = Thrift.serveIface(bindAddr(), new MyService[Future] {
  def myRPCFuction() {}
})
But, I found that the maximum number of concurrent requests is five( why 5? when more than 5, the server just ignore the excessed ones.) I look through the doc of Finagle really hard (http://twitter.github.io/finagle/guide/Protocols.html#thrift-and-scrooge), but find nothing hint to configure the max-request-limit. How to config the maximum concurrent request num of Finagle? Thanks

**Comment by mosesn** [comment]
@hliu20 could you describe your test environment?  And what kind of work are you doing in your myRPCFunction?  Are you just sleeping or busy-waiting?

**Comment by mosesn** [comment]
@hliu20 We have many machines which are running in production today, with much, much more than 5 concurrent requests, so I suspect there is something going on in your code or your environment.  If you have more information, I'm happy to help, but there's not a ton we can go on from this.  I'm closing this for now, feel free to reopen if you want to revisit.

**Comment by raultang** [comment]
new Thread(new Runnable {
    override def run(): Unit = {
      val client : Client = Redis.newRichClient("192.168.0.96:6379")
      while(true) {
        client.get(StringToChannelBuffer("111")).onSuccess( response => {
          println(CBToString(response.get))
        }).onFailure( error => {
          println(error.getMessage)
        })
//        TimeUnit.MILLISECONDS.sleep(1)
      }
    }
  }).start();


This will block after several times print , is it really have limit there and how to configure?

**Comment by raultang** [comment]
All right, it is because GC is full , seems client use quit a lot memory.

**Comment by mosesn** [comment]
It doesn't have a limit, but because finagle is asynchronous, you're sending many, many, many requests to the server, and because redis is pipelined, it's all through one tcp connection.  Each thread has to keep track of every request that it has been sent so far, so basically you're turning finagle into a queue where you put things in faster than you can take them out.

Note that it only prints when the server responds, so you're limited by both how fast your client can read responses off the wire (impacted by GC), and how fast the server can respond.
