### ISSUE TITLE
No handshake timout on SSLHandler

### ISSUE THREAD

**Issue by sirmax** [twitter/finagle#345]
`Netty3Transporter` does not set explicit handshake timeout on `SSLHandler`.

If a channel configured this way establishes TCP connection with a remote that does not respond to a handshake, the channel would get stuck in "connecting" state indefinitely.

This may cause various problems. One that I'm aware of is with the `FailFastFactory`.
When `FailFastFactory` tries to establish a connection it sets no timeouts on its own [1], thus it could be driven into a permanent fail-fast state, even if the connectivity with the remote service is long ago reestablished.

FYI, Netty 4 has a default handshake timeout of 10 seconds that can be overridden [2].
Unfortunately, it should be done explicitly in Netty 3, and the only way to do it is via a multi-arg `SSLHandler` constructor [3].

---

[1] – https://github.com/twitter/finagle/blob/6.22.0/finagle-core/src/main/scala/com/twitter/finagle/service/FailFastFactory.scala#L105
[2] – https://github.com/netty/netty/commit/817309c#diff-2fe7b22a8d650f1ea0bf56a809c061f9R237
[3] – https://github.com/netty/netty/blob/netty-3.6.4.Final/src/main/java/org/jboss/netty/handler/ssl/SslHandler.java#L370

**Comment by mosesn** [comment]
Rad, can you make a PR?

**Comment by sirmax** [comment]
I can, eventually. But it could take some time to make a proper PR with tests and stuff.

BTW @mosesn, what solution to this problem would you prefer? A timeout in Netty's `SslHandler` or in Finagle's `SslConnectHandler`? A fixed 10s timeout or a configurable one?

**Comment by vkostyukov** [comment]
Very interesting. We can add timeout to `Netty3TransporterTLSConfig` and override it with stack param. See examples [here](https://github.com/twitter/finagle/search?utf8=%E2%9C%93&q=Netty3TransporterTLSConfig).

**Comment by mosesn** [comment]
Let's just use `SslHandler`'s multi-arg constructor.  I agree with @vkostyukov that it should be configurable.

**Comment by vkostyukov** [comment]
@sirmax how is it going with handshake timeout? Just let us know if you need any help with that.

**Comment by sirmax** [comment]
@vkostyukov, sorry guys, I'm yet to find a time for this :( Tomorrow maybe.

As for the help, hint me on testing this thing, please. I thought about creating a pipeline and checking whether the `SslHandler` is properly configured, but maybe you have a better idea.

**Comment by vkostyukov** [comment]
@sirmax you may have a look at [this test](https://github.com/twitter/finagle/blob/develop/finagle-core/src/test/scala/com/twitter/finagle/netty3/Netty3TransporterTest.scala#L191). It also tests the `SslHandler` behaviour so you can use it as a start point.

**Comment by luciferous** [comment]
@sirmax put some work into this, but it looks like we still need to address a few things. From his comments on the closed PR:
> - In this PR I tried to fix #345 by adding an SSL-specific configuration parameter. Later we concluded it was not a good idea.
> - @mosesn was against re-using Transporter.ConnectTimeout for SSL, and he's probably right. It would be more like a workaround hack than a proper fix.
> - The proper fix should be somewhere around FailFastFactory. I can't yet pinpoint where exactly it should be.

**Comment by vkostyukov** [comment]
I'm working on TLS/SSL support in `finagle-netty4` and I remembered this thread. Wanted to make sure I'm not missing the handshake timeout problem @sirmax discovered a year ago.

Here is my understanding of the things (I read carefully through #346 twice).

1. The default handshake timeout is 10 seconds in Netty 4, which is good
2. We don't want to reuse `ConnectTimeout` param for this since the handshake should be considered a part of session acquisition, rather then TCP connection establishment
3. In my current implementation, we also delay the connect promise satisfaction until we've done the handshake. We shouldn't worry about connect timeout applied here since it will be applied onto an underlying promise that corresponds to an actual TCP connect.
4. My take is that the handshake timeout should be enforced via `TimeoutFactory` (disabled by default) and I'm not sure we need finer grained timeout here given that default 10 seconds one will prevent FailFact factory from stalls

Sorry if it wasn't clear, but I was trying to make a conclusion that we probably don't need to do anything else here for Netty 4 implementation. Please, let me know if you feel opposite.

**Comment by mosesn** [comment]
@vkostyukov I think it would be nice to have the `TimeoutFactory` timeout be able to interrupt the ssl handshake, but I agree that it's not urgent.  I think we shouldn't do anything until we run into a problem with it.

**Comment by vkostyukov** [comment]
Thanks @mosesn! I think so too! Actually, while rethinking this, I realized that there is a resource leak in the current implementation for Netty 4 - going to fix that today.

**Comment by mosesn** [comment]
We're just going to use a default timeout in TLS in netty 4 to simplify this, so I'm going to mark this as closed.  Please feel free to reopen it if you'd like to rediscuss this!
