### ISSUE TITLE
Declarative HTTP dsl with interpreter monad

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#406]
As discussed at the Dirty Water, it would be nice to have a declarative DSL to write http requests and an interpreter for the http monad.

**Comment by mosesn** [comment]
Is this in-scope for finagle?  finagle-http is such a weird mishmash of things that it is probably in-scope for finagle-http, but it would be nice to start reining in the http API and separating things out into a separate utility library.

With that said, this sounds like a cool idea in general.  It might be useful to take a look at [dispatch][0] too to see what worked / didn't work in that DSL.

Also, what's an http monad?

[0]: http://dispatch.databinder.net/Defining+requests.html

**Comment by travisbrown** [comment]
@spockz We're [planning to add](https://github.com/finagle/finch/issues/228) an HTTP client DSL to Finch that would mirror the request reader and encoding and decoding abstractions, but there's no definite timeline for that work.

**Comment by mosesn** [comment]
I'm going to close this feature request for now, since I'm not sure that this is in-scope for finagle right now.  Since this ticket was filed, @jeremyrsmith published [featherbed][0] which I think solves a similar problem.  We can revisit this in the future if simplifying the http `Request` and `Response` types doesn't help.

[0]: https://finagle.github.io/featherbed/doc/01-basic-usage.html
