### ISSUE TITLE
[finagle-mysql] finagle-mysql 6.25.0: Can not read UNSIGNED INT columns correctly

### ISSUE THREAD

**Issue by fab-soundcloud** [twitter/finagle#438]
Given this table:

```
CREATE TABLE `batches` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_unicode_ci;
```

with this data:

```
INSERT INTO `batches` (`id`)
VALUES (4294967295);
```

Trying to load that row with finagle mysql via pseudo code:

```
PreparedStatementQuery("SELECT * FROM batches WHERE id = ?").select(4294967295L)
```

results in this value being available in the pattern matching:

```
IntValue(-1)
```

It looks like mysql-finagle does not understand UNSIGNED int's which should result in a LongValue() or at least a Long java/scala representation. It always parses an Int which MaxValue is:

```
scala> Int.MaxValue
res0: Int = 2147483647
```

The problematic code I guess is this:

https://github.com/twitter/finagle/blob/develop/finagle-mysql/src/main/scala/com/twitter/finagle/mysql/Row.scala#L74 

Expected behaviuor would be the that I can successfully read the value 4294967295 back somehow.

**Comment by mosesn** [comment]
@fab-soundcloud good catch!  Unfortunately, we don't have a ton of bandwidth right now, but we'd love to shepherd your PR through :+1:

**Comment by mehmetgunturkun** [comment]
Hi @mosesn, I am willing to solve this issue, now working on it. 
Should I assign this issue to myself?

**Comment by mosesn** [comment]
@mehmetgunturkun it looks like I can only assign it to committers, but feel free to start working on it!  I'll just mark it as "in progress".  Thanks, and welcome to the project!

**Comment by mehmetgunturkun** [comment]
Hi @mosesn, I guess I solved the issue but before creating a pull request there are several things that I want to ask:
1. Should I talk to people in gitter.im about the way I solve the issue or these comments will be done in code review before the merger?
2. In order to understand unsigned part, I used flags in the field data. There was no documentation for bits and their locations per each attribute in mysql side, so I dug into source code and find the bit masks for each attribute. I want to document this process and put a link to that source code so that nobody again needs to do this research. How should I do that?

P.S. Sorry if I shouldn't have written these into issueç

**Comment by kevinoliver** [comment]
This [got fixed](https://github.com/twitter/finagle/commit/598acc5416798d37e4c796ab115cbda9a34fb787) a little while back. See [this unit test](https://github.com/twitter/finagle/blob/develop/finagle-mysql/src/test/scala/com/twitter/finagle/mysql/integration/TypeTest.scala#L253-L260) for an example.
