### ISSUE TITLE
client: connection closes on request timeout

### ISSUE THREAD

**Issue by pikazlou** [twitter/finagle#455]
Hi.
I'm working with HTTP client and I've noticed that any kind of request exception causes the connection to close. This includes timeout exceptions.

Unfortunately my client has to send requests to remote servers and at the same time has to provide response (if any) fairly quickly. So getting decent percent of timeouts is a usual thing. But then each timeout (whether implemented through ```ClientBuilder.timeout()``` or through ```Future.raiseWithin()```) results in connection close. Which makes impossible to reuse connections.

This is a serious issue for me, since the client has to perform 2-3k requests per second. Currently lots of tcp connections are constantly created and then thrown away.

Is it possible not to close connection and implement HTTP keep-alive while having timeouts enforced?

**Comment by mosesn** [comment]
What you're running into is that when we signal an interruption to the `Future` that's going to return a result from a remote server, it considers that a request to discard the work, so it cuts the connection.  We use tearing down a connection in http to signal to the server that we no longer care about the work.  If you don't have to tear down the connection, I would recommend not interrupting the request.  Instead of `Future#raiseWithin`, for example, you can take a look at `Future#within`.  Another option would be to mask the future explicitly, which you can do with `Future#masked`.

We're currently looking into http2 support, where we'll be able to use http2 interrupts to avoid having to tear down the connection to signal to the remote server we no longer care about the work, but that's a few months down the line.  If you control the remote servers, you can also consider using thriftmux instead, where we already support this functionality.

One other option is to choose your timeouts less aggressively, or to use `BackupRequestFilter`.  If you're doing 3K QPS and need to tear down more than a few connections per second, it might be worth looking into why that is and trying to fix that.

**Comment by mosesn** [comment]
I'm going to close this ticket, since we can't really do better on http/1.1
