### ISSUE TITLE
question: finagle-stats histogram windowing behavior

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#492]
I was under the impression that finagle's histograms are windowed.

We're observing some odd behavior via our process's admin interface, and I've been able to reproduce it with:

```sh
while true ; do
  curl -s "$HOST:9990/admin/metrics.json" | \
    jq -M '.["rt/out/dst/id/io.l5d.k8s/default/http/word/request_latency_ms.p99"]'
  sleep 1
done
```

Typically, we see values pinned for ~a minute.
```21
21
21
21
21
21
21
21
21
21
21
21
21
21
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
33
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
34
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
205
```

I was under the impression that finagle-stats' histograms are windowed to 60s and so updates are not reflected in a finer granularity.

HOWEVER--at other times (without doing anything), sometimes these stats will spontaneously start returning variable secondly values:
```
27
20
20
27
20
11
75
30
20
25
```

This behavior can occur for ~several minutes before returning to being pinned.

This behavior occurs across _all_ (latency) histograms.  I.e. for multiple clients either they are _all_ pinned_ or _all_ variable.  The only thing we're doing to the process is (1) sending traffic through it and (2) polling the admin port.

The process in question has been running for nearly two days, so this problem is not related to start-up.

### Questions ###

1. What is the _expected_ behavior for histograms?
2. Are there any possible explanations?
3. If this is secondly, what are the properties of this histogram? What range of values are being measured?
4. If this is supposed to be minutely, does this indicate that sometimes minutely data is 
5. What additional data can I provide to help debug this?

All in all, we would _like_ access to higher-granularity latency information.  However, most importantly, we want the behavior to be predictable, or at least explainable.

**Comment by mosesn** [comment]
1.  Expected behavior is that they're only changed minutely.
2.  Hmm, maybe.

There are a few weirdnesses:

We're using System.currentTimeMillis instead of System.nanoTime for measuring a duration: https://github.com/twitter/twitter-server/blob/a569edc24aca5935389d8ae498aa5abdb05cdcc1/src/main/scala/com/twitter/server/util/MetricSource.scala#L21

We update secondly in MetricSource:
https://github.com/twitter/twitter-server/blob/a569edc24aca5935389d8ae498aa5abdb05cdcc1/src/main/scala/com/twitter/server/util/MetricSource.scala#L19

We also use System.currentTimeMillis instead of System.nanoTime for measuring a duration here:
https://github.com/twitter/finagle/blob/develop/finagle-stats/src/main/scala/com/twitter/finagle/stats/MetricsBucketedHistogram.scala#L73

We assume that a metric will be queried at least minutely for every minute after it starts.  If you don't, we will snapshot as often as you want until you catch up (I suspect this is the problem you're running into).
https://github.com/twitter/finagle/blob/develop/finagle-stats/src/main/scala/com/twitter/finagle/stats/MetricsBucketedHistogram.scala#L73-L75

@yokoshin pointed this behavior out on this thread, and we've been playing around with a few ideas for how to improve this: https://github.com/twitter/twitter-server/issues/33.  Would love your feedback.

**Comment by olix0r** [comment]
It appears that this behavior may occur when /admin/metrics.json hasn't been read from in over a minute?

```sh
:; function fetch_count(){ curl -s "$HOST:9990/admin/metrics.json" |jq -M '.["rt/out/dst/id/io.l5d.k8s/default/http/word/request_latency_ms.count"]' }
:; sleep 300 ; while true ; do fetch_count ; sleep 1 ; done
```
```
55093
315
153
117
102
543
23
35
23
26
26
26
26
26
26
```

This is surprising behavior!  What's the thought process behind it?  I think it would be helpful to have this behavior documented in the guide. (I don't understand it well enough yet to write try to do this).

Ultimately, it seems the behavior should be determined _by the client_ and not by the server.  I.e. I don't think I should have to choose between Metrics StatsReceiver and ImmediateMetricsStatsReceiver _in code_.  Rather, the requester of stats should determine what view of the data is needed.

That said, it still seems very surprising behavior for metrics latching to occur only when metrics are requested and not at some fixed interval...

**Comment by olix0r** [comment]
@mosesn ah yes, that behavior documented in that ticket sounds correct -- I get secondly data for as many seconds as minutes I have not requested metrics!  This sounds like a bug.

Outside of that bug, I'll try to formulate a better idea on how I'd want this to work.

**Comment by mosesn** [comment]
Jinx!  Let's move discussion to the TwitterServer thread.

**Comment by mosesn** [comment]
You already fixed this here https://github.com/twitter/finagle/pull/495 so I'm going to close this ticket.  Thanks for the contribution @olix0r!
