### ISSUE TITLE
netty4: leak detected

### ISSUE THREAD

**Issue by olix0r** [twitter/finagle#508]
When sending a moderate amount of load on a netty4-http server/client, I observe the following in the logs:
```
E 0519 20:25:23.442 THREAD76 io.netty.util.ResourceLeakDetector.reportLeak: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.
```

**Comment by dschobel** [comment]
we turn off leak detection because we leak every inbound buffer into application code and let the GC handle it so the leak isn't a surprise, but the detector shouldn't be jibber jabbering either.

https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/package.scala#L40

can you post your client/server config to reproduce?

**Comment by dschobel** [comment]
@olix0r are you still seeing this?

**Comment by olix0r** [comment]
sorry, I think this is something I only ever saw out of `sbt run` (and i haven't run it this way recently)..  It's relatively minor and probably not worth spending time on. Closing.
