### ISSUE TITLE
`com.twitter.finagle.http.filter.StatsFilter` is missing a corresponding module

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#556]
`com.twitter.finagle.http.filter.StatsFilter` Is missing a corresponding module so it cannot be conveniently added to a Stack.
### Expected behaviour

Adding/enabling the HTTP Stats should be as adding an extra module to the stack. Ideally, this should be possible with the `with*` methods of Client.
### Actual behaviour

Currently one has to create the module itself and decide where to put it.

**Comment by kevinoliver** [comment]
Not against creating a module for it but I'm not sure we want this module in the default stack for Http, so you'll still need to decide where to place it. Alternatively, since I think you'll want this at the beginning of the chain (so that it sees the final responses and total time) you could also  this `Filter` on top: `new http.filter.StatsFilter(..).andThen(Http.client.newService)`

**Comment by spockz** [comment]
It doesn't need to be in the stack by default. It's just that I would like to be able to add it through an existing `withHttpStats` (or similar) on the client. We do add the filter now but I would like to re-use the StatsReceiver from the stack because that is the one that is going to be set anyway. Otherwise, the StatsReceiver has to be passed manually to the StatsFilter which is error prone, on top of being tedious.

- Alessandro

**Comment by kevinoliver** [comment]
Ah. Yeah, that reason makes sense to me too. Feel like putting together a PR?

**Comment by spockz** [comment]
@kevinoliver sure, see #557.

**Comment by kevinoliver** [comment]
@spockz I think #557 addressed this so I'm closing it. Please reopen if I got that wrong.
