### ISSUE TITLE
Preventing double computation

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#575]
When using response classifiers we need to compute values multiple times. 

E.g. to check whether a response is functionally valid we parse the result as JSON and check some fields. To do this the JSON is parsed in both the response classifier as our filter that transforms an HTTP response into an object. Another use-case is SOAP Messages, we need to validate and parse the XML to see whether the message is a SOAPFault or not.

After a little brainstorming the following ideas came up:

# Solution 1
Move the transforming filters that normally are pushed on the Service after creating the client into the instance level stack so that failures in the filters are automatically counted.

Pros:
* Re-use of both transformation code
* Re-use of computed values, as opposed to what happens in the thrift-library where only one step, the deserialisation of bytes to object, is cached.

Cons:
* For every action/type of request a new client instance is needed, this overly complicates things, e.g. if we want to send multiple requests to the server that have different response types.

Note: this would also solve the discussion we had on whether Finagle should transform responses that are classified as failure to actual Failures.

# Solution 2
Like 1 but a bit more 'dynamic'. Instead of doing the response transformation inside the filter itself, the filter might push the transformation onto a list(stack?) in a local context. These transformations in the local context would then be applied by a new, to be created, filter in the instance stack. Again, any failures would automatically count towards failure-accrual.

Pro:
* Re-use of both transformation code
* Re-use of computed values
* Re-use of client/connection instances

Cons:
* Spaghetti, harder to reason about what happens where
* Dynamic, so what about type-safety?

# Solution 3
The Failure Accrual mechanism is exposed to the response transformers higher up the chain. If one of them fails it can notify the failure-accrual counter in the instance stack that the response was a failure. Maybe this could be implemented by adding a callback to the local-context that would increase the counter or something along those lines.

Pro:
* An explicit interface is created for classifying failures down the line
* Computation happens only in one place, thus it doesn't need to be shared
* Filters can stay the same

Cons:
* How should this be used with the, also clean, `ResponseClassifier` API?

Solution 3 has my vote because it is specific to what we are trying to solve and it has no clear cons.

**Comment by mosesn** [comment]
@spockz we already only deserialize only once in thrift.  this is enforced by [DeserializeCtx][0].  it might make sense to try to raise DeserializeCtx to finagle-core if it will be useful for http too.

[0]: https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/scala/com/twitter/finagle/thrift/DeserializeCtx.scala#L29-L41

**Comment by spockz** [comment]
@mosesn that is exactly what I was alluding to in the second pro of solution 1. The issue with that solution that it only works for one transformation. In the SOAP example we parse SOAP but the application then still transforms the contents of the SOAP response and has to check for functional errors.

**Comment by kevinoliver** [comment]
@spockz re #1, this approach was discussed as an alternative design for response classification but we decided against it for two reasons. 1, it meant users had to do "data modeling" for their failures. 2, it would be a significant change for existing code to use response classification, and thus a barrier to adoption.

re #3, i see the appeal of exposing the failure accrual to the application. not sure whether or not to pursue this, but a sketch might be something like:

- replace the failure accrual module in the stack with a tweaked failure accrual module that adds a local context for you to callback in with the results for the right node instead of using the response classifier to make the decision on a req/rep.
- in application code, pull that context out after your business logic and call successful/failed on it.

you might also want to remove the success rate stats and do it in application code as well. this is  already doable now for you.

**Comment by mosesn** [comment]
@spockz was going through old issues and saw this one was still open.  how do you think we should proceed?

**Comment by spockz** [comment]
@mosesn and @kevinoliver: if you believe #3 to be a viable solution we can try to implement it and use it in our application. And, if we like it, contribute it back.

The only snag that I see is on how to expose/provide the method that classifies a request/response as a failure. Using Context.Local would mean that the method isn't available before, possibly in a filter, where we set the context. If the FA module sets the context is only available lower down the call chain, right?

**Comment by mosesn** [comment]
@spockz you should be able to use normal call-back mechanisms.  For example, you could have the call-back satisfy a future.  I'm going to close this ticket for now since it seems like you have a solution–if you decide you think it's worth contributing back, please make a PR!  Feel free to reopen if there's more to discuss.
