### ISSUE TITLE
Finagle 6.41.0 building failed 

### ISSUE THREAD

**Issue by darionyaphet** [twitter/finagle#576]
Finagle 6.41.0 building failed .

### Expected behavior

`./sbt` maybe should make this project .

### Actual behavior

```
λ ~/source/finagle-finagle-6.41.0/ ./sbt 'run-main Server'
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by mosesn** [comment]
I googled that error, and it looks like you run into that when you try to run a git command but you're not in a git repository. I don't think ./sbt has any git commands (as far as I know), and besides, finagle is a git repository if you downloaded it from GitHub. I think you might have something weird going on on your end.

as an aside, I don't know what server you expect to run with run-main, since finagle is a library. 

what are you trying to do?
