### ISSUE TITLE
Provide metrics endpoint for influxdb line protocol

### ISSUE THREAD

**Issue by wei-hai** [twitter/finagle#625]
Please provide metrics endpoint for influxDB line protocol.

**Comment by mosesn** [comment]
@wei-hai I don't think this is in scope for the finagle project itself, but finagle is intentionally extensible so that you can add this yourself.  The linkerd project, which is built on top of finagle, has done this [here][0].  I would encourage you to make your own finagle-influxdb project, like [finagle-metrics][1] and that way other people can benefit from your work!  The linkerd stuff looks like a good start, although you would probably want to supply your own StatsReceiver.  I'm going to close this ticket for now, but please let us know if you have any further questions.

[0]: https://github.com/linkerd/linkerd/blob/master/telemetry/influxdb/src/main/scala/io/buoyant/telemetry/influxdb/InfluxDbTelemeter.scala
[1]: https://github.com/rlazoti/finagle-metrics
