### ISSUE TITLE
SingletonPool does not close the underlying services

### ISSUE THREAD

**Issue by adleong** [twitter/finagle#626]
SingletonPool does not close the underlying services.

https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/pool/SingletonPool.scala
When SingletonPool creates a new RefCountedService, it initializes it with a ref
count of 1.  It then calls `open` on this service before returning it resulting
in the service having a count of 2.  Calling close on this service only
decrements to 1 meaning the underlying service is not closed.

### Expected behavior

Calling `close` once on a newly created service from a SingletonPool should
close the underlying service.

### Actual behavior

Newly created services are returned with ref count of 2 and therefore calling
`close` does not close the underlying service.

Please let me know if I have misunderstood the intention of this code.  If I 
understand correctly, the ref count should be initialized to 0 instead of 1
because `open` will be called on the service.

**Comment by kevinoliver** [comment]
@adleong i believe it is intentional. note the [scaladoc commentary](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/pool/SingletonPool.scala#L26-L36).

while working on `MethodBuilder` i had a need for a similar construct but chose to implement [`RefcountedClosable`](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/client/RefcountedClosable.scala) instead. 

that said, maybe there's a bug or another issue? a unit test showing a leak might help illuminate.

**Comment by roanta** [comment]
The reason it's initially set to 1 is because the finagle client uses `close` to signal the release of a session/connection. This allows the underlying pool implementations to interpret it and act accordingly.

For example, a common [1] way to use a client:

```
client().flatMap { service => 
   service(req).ensure { 
       service.close() 
   }
}
```

If the `close` here would actually tear down the session, the client would churn through resources.

[1] https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/Service.scala#L293-L310

**Comment by adleong** [comment]
Ah I see.  So it's intentional that the underlying session is left open even when all clients have released it?  And the only way to actually tear down the session is to call close an extra time?

```
client().flatMap { service => 
   service(req).ensure { 
       service.close() // release this client's session
       service.close() // actually tear down the underlying service
   }
}
```

**Comment by roanta** [comment]
The additional close is more likely to come from tearing down the client entirely (i.e. calling close on the client):

https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/pool/SingletonPool.scala#L187-L188

**Comment by adleong** [comment]
Got it.  Thank you for explaining this to me!
