### ISSUE TITLE
Finagle Client: TLS Host name verification

### ISSUE THREAD

**Issue by iyogi** [twitter/finagle#639]
SslHostVerificationException is thrown when a Finagle HTTP client is configured with multiple remote endpoints over TLS, with each remote server installed with TLS certificates with distinct Subject Alternative Name (SAN).

Given below is a representation of how our HTTP client is configured in our (java based) application:

_Http.client()
.withTls("**node1.example.com**")    //(A)
.newService(Resolvers.eval("**node1.example.com:443, node2.example.com:443**"),   //(B)
"NodesAPI");_

Each node in the cluster defined in (B) has TLS certificates installed containing SAN as their respective domain names - node1.example.com has SAN "node1.example.com" and node2.example.com has TLS certificate with SAN as "node2.example.com"

During SSL handshake, when _com.twitter.finagle.ssl.SessionVerifier_ is verifying the hostname in (A) above to the SAN name in the certificate of the connented remote server, the check will fail if finagle client happens to connect to node2.example.com.

Is it possible to keep the host verification check as well as allow configuring multiple remote end points in HTTP client, but allow for configuring multiple TLS host names in A above and update the SessionVerifier to check that the SAN in the certificate should match **_any_** of the configured host names?

### Version

- finagle (com.twitter:finagle-core_2.11:jar:6.35.0 and com.twitter:finagle-http_2.11:jar:6.35.0)
- Java 1.8.0_121

**Comment by ryanoneill** [comment]
Hi @iyogi, with the next release of Finagle, which should happen sometime this month, you'll be able to specify your own `SslClientSessionVerifier` as part of your SSL/TLS setup. This would allow you to verify the hostname as you see fit, instead of getting rejected by the `HostnameVerifier`.

Since it's not published yet, I'll link to our develop branch, which contains the most recent changes. See [ClientTransportParams](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/param/ClientTransportParams.scala#L63) for details.

**Comment by kevinoliver** [comment]
I believe this is now possible.
