### ISSUE TITLE
Missing RCP documentation

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#680]
I´m looking forward to use RPC thrift using scrooge plugin and implementation of Finagle, but to be honest, it's impossible to find any updated and official documentation. So I´m start wondering, Are you guys abandon the implementation of RPC and now the project that you guys use is Finatra?.

Regards

**Comment by mosesn** [comment]
@politrons where have you looked so far?  We have documentation both for [scrooge][0] and for [finagle][1].  If you've already looked at these, could you elaborate on what you're missing?

[0]: https://twitter.github.io/scrooge/Finagle.html
[1]: https://twitter.github.io/finagle/guide/

**Comment by politrons** [comment]
I think the problem is that you guys have several documentation for older versions of scrooge which are not working anymore with newest finagle versions published.
 
It's feel like scrooge it´s not part of Finagle project since there's no track of it from the official finagle web page.

Can I use this question to ask you if there´s any implementation of Streaming with Thrift + scrooge?

**Comment by mosesn** [comment]
@politrons which documentation is for an older version of scrooge?  the one I linked you to should be current.

We link to scrooge in finagle under the "protocols" section, here: https://twitter.github.io/finagle/guide/Protocols.html?highlight=scrooge.  Please feel free to open a pull request if you have ideas for how we could improve the documentation.

We don't currently have a thrift streaming implementation, in large part because the thrift protocol doesn't support streaming.  We're looking into different possible implementations though.  How are you intending to use thrift streaming?

**Comment by politrons** [comment]
I cannot find where I saw the old documentation. Regarding the streaming we´re using gRPC using bidirectional StreamObserver to connect some microservices, but I would love it migrate it to Scala. Unfortunately people from Google does not like Scala :( that´s the reason why I start looking into Thrift

**Comment by mosesn** [comment]
I'm not a grpc expert, but my understanding is that grpc's thrift is actually sending thrift messages over HTTP/2, speaking a grpc-specific protocol.  We don't support that protocol today, although we might support it in the future.  Thrift in general doesn't support streaming, so I think you may have a difficult time migrating off of grpc without supporting two clients for a little while.

If you want to use scala, but also want to continue using the grpc thrift protocol, scala typically makes it easy to call java from scala, so I would encourage you to continue using grpc-java, and call it from scala.

If you wanted to use finagle's HTTP/2 implementation to speak with a grpc remote peer, there are a few possible complications.  The one that would probably be the largest impediment is that our HTTP implementation doesn't support HTTP trailers.  Trailers were considered fringe before grpc (as an example, browsers don't support HTTP trailers), and we haven't had a chance to implement them since grpc became popular.

**Comment by politrons** [comment]
Thanks I´ll keep in mind, and I will see if it's worth it the migration since if all the generate code by gRPC it´s already in Java there's nothing to migrate actually.
