### ISSUE TITLE
Finagle Thrift NoSuchMethodError

### ISSUE THREAD

**Issue by politrons** [twitter/finagle#681]
I´m using Finagle thrift but when I build the server and service
```

      val service = new EchoService$FinagleService(new EchoServiceImpl, new TBinaryProtocol.Factory())
    
      val server = Thrift.server.serveIface("localhost:8080", service)
```

And I run it and I receiving the exception:

```
    Exception in thread "main" java.lang.NoSuchMethodError: com.twitter.finagle.server.StackServer.$init$(Lcom/twitter/finagle/server/StackServer;)V
    	at com.twitter.finagle.Thrift$Server.<init>(Thrift.scala:417)
    Disconnected from the target VM, address: '127.0.0.1:60647', transport: 'socket'
    	at com.twitter.finagle.Thrift$.server(Thrift.scala:495)
```

**Comment by mosesn** [comment]
@politrons from the [javadoc][0]:

> Thrown if an application tries to call a specified method of a class (either static or instance), and that class no longer has a definition of that method.
>
>Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

Sometimes this happens if you're trying to use two libraries that are incompatible.  Make sure you're using the same version of scrooge and finagle, and that you haven't cached anything that you compiled with an older version of finagle.

[0]: https://docs.oracle.com/javase/7/docs/api/java/lang/NoSuchMethodError.html

**Comment by politrons** [comment]
Yeah it was mixing code from previous version with new one.
