### ISSUE TITLE
question: how to generate a unique and contiguous id for a single service

### ISSUE THREAD

**Issue by cch123** [twitter/finagle#881]
I don't know whether it's proper to put the question here, if not please tell me where to ask questions ~

in Finagle deterministic aperture document, it said:

> This information can be configured in the ProcessCoordinate object by setting the processes instance number and the total number of instances. The current implementation requires that all instances in the cluster have unique and contiguous instance id's starting at 0.

I wonder how to get this **unique and contiguous** id, I may need to change our service discovery system to accomplish this, or make all the services to depend on an extra id generator, or something else?

**Comment by bryce-anderson** [comment]
Sorry for the long delay, chances are you're no longer interested, but I'll answer the question regardless.

There are a number of strategies for this. The best strategy is to work in tandem with your job scheduling system and let it assign names. For example, if you have Service A, it's 4 instances would ideally be named something like `A/0, A/1, A/2, A/3`. This needs to be available to your instances (A/1 needs to know it's A/1 out of 4 members) so they can set their identity as instance 1, or really as 1/4.
This can also be done by interacting with the naming service so long as an instance can recognize itself. An instance can define its order by sorting the host:port pairs and know where its own host:port sits in that ordering.

Note that when doing this ordering, it's good to _determinstically_ add some entropy. For example, instead of simply sorting instance ID's from the scheduler, instead hash each ID using a method that will result in unique id's (either guaranteed or sufficiently unlikely to collide that it will realistically never happen) and use that as the order. This is to avoid things like having a deployment process which goes in batches of 10 wipe out 10 members from one client and nothing from the others, and instead distributes the losses across the ring.

**Comment by cch123** [comment]
@bryce-anderson , thx very much

> For example, if you have Service A, its 4 instances would ideally be named something like A/0, A/1, A/2, A/3. This needs to be available to your instances (A/1 needs to know it's A/1 out of 4 members) so they can set their identity as instance 1, or really as 1/4.

So service A needs to know the total number of its instances, when the service scales out to more instances, how do these instances be notified about this change? (Maybe subscribe itself in the service discovery system?

**Comment by hamdiallam** [comment]
Yes for the **total** number of instances, the host should subscribe to the service discovery system about its own cluster to determine this.

For the instance id, there's a few ways to determine this as Bryce mentioned

**Comment by cch123** [comment]
@hamdiallam ,  thx for your reply
